---
- hosts: all
  roles:
  - { role: hnakamur.osx-rbenv, rbenv_ruby_version: 2.1.6 }
  - { role: hnakamur.oh-my-zsh, oh_my_zsh_theme: gallois }

  tasks:
  - homebrew: update_homebrew=yes
  - homebrew_tap: tap=caskroom/cask state=present
  - homebrew_tap: tap=homebrew/science state=present
  - homebrew_tap: tap=caskroom/versions state=present
  - homebrew_tap: tap=caskroom/fonts state=present
  - homebrew_tap: tap=neovim/neovim state=present

  - name: install homebrew packages
    homebrew: pkg={{ item }} state=present
    with_items:
      - nodenv
      - nodejs
      - git
      - zsh
      - vim
      - the_silver_searcher
      - ctags
      - reattach-to-user-namespace
      - tmux
      - docker
      - go
      - r
      - heroku-toolbelt
      - s3cmd
      - awscli
      - aws-elasticbeanstalk
      - jshon
      - sysdig
      - dnsmasq
      - wget
      - postgresql

  - name: install homebrew casks
    homebrew_cask: name={{ item }} state=present
    with_items:
      - iterm2
      - macvim
      - virtualbox
      - vagrant
      - caffeine
      - alfred
      - atom
      - omnifocus
      - textexpander
      - evernote
      - skitch
      - spotify
      - skype
      - github
      - reggy
      - bartender
      - vlc
      - sourcetree
      - flux
      - charles
      - rubymine
      - sublime-text
      - plex-media-server
      - fitbit-connect
      - colloquy
      - imageoptim
      - path-finder
      - cyberduck
      - kaleidoscope
      # - istat-menus
      - firefox
      - google-chrome-beta
      - google-chrome-canary
      # - google-chrome-dev
